spring.application.name=stockTrade

spring.datasource.url=jdbc:postgresql://localhost:5432/stocktrade?reWriteBatchedInserts=true&prepareThreshold=5
spring.datasource.username=postgres
spring.datasource.password=yash3035
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable Java Virtual Threads
spring.threads.virtual.enabled=true

# Tomcat HTTP Thread Pool (Requests queue me na latke)
server.tomcat.threads.max=500
server.tomcat.accept-count=2000
server.tomcat.max-connections=10000

# HikariCP DB Connection Pool Expansion (Timeout bachane ke liye)
spring.datasource.hikari.maximum-pool-size=60
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000


spring.output.ansi.enabled=ALWAYS

# Default Root Logger
logging.level.root=INFO

# Tumhare project package ke liye custom DEBUG mode
logging.level.com.tradingEngine.stockTrade=DEBUG

# Spring Boot 3.x / Spring Data Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6381